Video uploads with google drive API
MissouriMRR/paracord pull request #20
Opened 2020-04-15 02:46 UTC by JoshGuempel

Backend sends video uploads to google drive with a service account.

2020-04-15 04:03 UTC, ClayMav requested changes
Permissions are a big problem here, users on google drive need to be able to see the files. Also dont ask for a mimeType, just see what mimeType is provided and ensure that it is a video file. Test with a shared drive and make sure it works with one of those too. Squash and merge will be the move once this is done and approved

2020-04-16 19:14 UTC, JoshGuempel commented
Updated file uploads to work with shared drives, and also removed mimeType parameter from the video upload mutation.

2020-04-16 19:24 UTC, ClayMav requested changes

2020-04-16 19:24 UTC, ClayMav commented on api/file_manager/file_manager.ts
> +    })
I'm not sure you need to define the drive every time you do an action, why not create it globally and use it when you need it

2020-04-16 19:24 UTC, ClayMav commented on api/file_manager/file_manager.ts
> +    })
as above

2020-04-16 19:24 UTC, ClayMav commented on api/file_manager/file_manager.ts
> +    })
as above

2020-04-16 19:24 UTC, ClayMav commented on api/resolvers/video-resolver.ts
> +        { createReadStream, filename, mimetype }: Upload,
I would do a check to make sure that the mimetype is a video, check for the video files output from ios and android specifically as well as the common mp4, mov, etc

2020-04-16 21:31 UTC, ClayMav requested changes

2020-04-16 21:31 UTC, ClayMav commented on api/file_manager/file_manager.ts
> +    }
definitely move all this logic to the resolver for the video

2020-04-16 21:31 UTC, ClayMav commented on api/resolvers/video-resolver.ts
> +        }
Dont catch it, let it blow up

2020-04-17 22:37 UTC, ClayMav requested changes

2020-04-17 22:37 UTC, ClayMav commented on api/resolvers/video-resolver.ts
> +        await deleteFolder(video.driveId)
its a video not a folder, maybe rename the function

2020-04-18 00:38 UTC, ClayMav approved these changes

2020-04-18 00:49 UTC, merged